zebrunner/stf

lib/cli/ios-provider/index.js, lib/cli/local/index.js, lib/db/api.js, lib/units/app/middleware/webpack.js, lib/units/ios-device/plugins/wda.js, lib/units/ios-device/plugins/wda/WdaClient.js, lib/units/processor/index.js, lib/util/ios-usb.js, lib/wire/wire.proto, package-lock.json
IOS devices display by name, not by uuid.
Next step is extracting battery information, ios version ,build architecture.
Fixed error in regular expression.
=> Info blocks

lib/units/device/plugins/store.js, lib/units/ios-device/plugins/wda.js, lib/units/ios-device/plugins/wda/WdaClient.js, lib/units/websocket/index.js, lib/util/ios-usb.js, lib/util/iosutil.js, lib/wire/wire.proto, res/app/components/stf/control/control-service.js, res/app/control-panes/dashboard/apps/apps-controller.js
added : 
- reboot 
- camera
- search
- lock/unlock
- volume buttons 
- App Store
- Settings
=> Advanced tabs

lib/cli/local/index.js, lib/cli/processor/index.js, lib/units/processor/index.js
**The delete option was unused and could cause regression on android devices.**
=> #67: have been deleted connect-push opt from processor service

lib/cli/local/index.js, lib/cli/processor/index.js, lib/units/ios-device/index.js, lib/units/ios-device/plugins/connect.js, lib/units/ios-device/plugins/wda.js, lib/units/ios-device/plugins/wda/WdaClient.js, lib/units/processor/index.js
**This PL resolves this issue #65.**
Has been fixed bug with expired sessionId or invalid.
=> Develop bug fixing

lib/units/ios-device/index.js, lib/units/ios-device/plugins/info/IosDeviceParser.js, lib/units/ios-device/plugins/info/index.js
Have been created a plugin for saving and managing device info
=> #79 ios-device should output device's namve instead of udid

res/app/control-panes/control-panes-controller.js, res/app/control-panes/tree-elements/index.js
**Have been deleted tree tab from android device**
=> #78: Have been deleted tree tab from android device

res/app/components/stf/screen/index.js, res/app/components/stf/screen/screen-directive.js, res/app/components/stf/screen/screen-loader/index.js, res/app/components/stf/screen/screen-loader/screen-loader-directive.js, res/app/components/stf/screen/screen-loader/screen-loader.css, res/app/components/stf/screen/screen-loader/screen-loader.pug, res/app/components/stf/screen/screen.pug
introduce "loading" icon for iOS device while we connect to mjpeg and wda port #87
=> have been added screen loader #87

lib/units/ios-device/plugins/wda/WdaClient.js
…and get-screenshot actions
The fix of  - https://github.com/qaprosoft/stf/issues/105
=> Istf #105 refactored handlerequest and fixed rotation

lib/units/device/plugins/store.js, lib/units/ios-device/plugins/wda.js, lib/units/ios-device/plugins/wda/WdaClient.js
The PR will resolve the issue - https://github.com/qaprosoft/stf/issues/113
- Also have been transferred `wirerouter` initialization from `then` to `finally` in order to initialize`wirerouter` regardless of WDA's connection.
- Added middleware for WdaClient
=> istf#113: initialize wirerouter despite on WDA connection

res/app/components/stf/screen/screen.pug
https://github.com/qaprosoft/stf/issues/58
=> istf: have been disabled input automplete

lib/units/ios-device/plugins/wda/WdaClient.js
=> Revert "#411"

res/app/device-list/column/device-column-service.js, res/app/device-list/device-list-controller.js
=> added filtering by platform

res/app/device-list/device-list.pug
=> removed autofocus on search field on device list page

lib/units/ios-device/plugins/wda/WdaClient.js
=> added device restoring script calling on wda mjpeg disconnect

lib/units/ios-device/plugins/wda.js
Removing "GetIosTreeElements" code, since the tree tab was removed previously.
=> #675 Removing "GetIosTreeElements" code

lib/units/ios-device/plugins/wda/WdaClient.js
The following code prevents crashes when requesting the session of the device.
=> #687 1st session verification request fix

res/app/control-panes/advanced/input/input.pug
The following code should disable media buttons in iOS devices.
=> #711 Testing: disabling media buttons in iOS devices

lib/units/ios-device/plugins/wda.js, res/app/control-panes/info/info.pug
The following code should disable the find button in iOS devices.
=> #469 Testing: disabling find device button in iOS devices

lib/units/websocket/index.js, res/app/components/stf/control/control-service.js, res/app/control-panes/info/info.pug
The following code is a test to open Find My app with the finder button.
=> #469 Testing: Find device button fix

res/app/control-panes/advanced/device-settings/device-settings.pug
The following code disables WiFi buttons in iOS devices.
=> #466 Disable WiFi options in iOS devices

res/app/control-panes/advanced/device-settings/device-settings.pug
The following code only disables the buttons for iOS devices.
=> #467 Disabling ringer buttons for iOS

res/app/control-panes/info/info-controller.js, res/app/control-panes/info/info.pug
The following code calls the `finder()` function, which should emit the `PhysicalIdentifyMessage` wda event (in order to open 'Find My' application).
=> #469 Testing: finder function inside info-controller.js

res/app/control-panes/dashboard/install/install.pug
Related issue: https://github.com/zebrunner/stf/issues/404
=> #404 Adjusting install error styles

res/app/control-panes/dashboard/install/install.pug
The following code provides the necessary modifications to contain the error text inside the alert.
=> #404 Fixing installation error text

res/app/control-panes/info/info.css, res/app/control-panes/info/info.pug
=> fixed info tab layout on device control page (issue #745)

res/app/components/stf/device-context-menu/device-context-menu.pug
The following code disables the panel buttons that are not supported in Apple TV wda
=> #756 Disable back, recents and rotate buttons

lib/units/ios-device/plugins/wda.js, lib/units/ios-device/plugins/wda/WdaClient.js
=> Revert "#177 Draft: Fixing error in RotationIosEvent"

lib/db/index.js
The following code attempts to reconnect to the DB every 5 seconds.
=> #726 DB connection recovery

lib/units/ios-device/plugins/wda/WdaClient.js
The following code implements a function call that sets the device version into the DB.
=> #234 (mcloud-ios) Setting iOS version in WdaClient

lib/units/ios-device/plugins/wda/WdaClient.js
The following code removes the kickstart launch (which is not necessary since mcloud-ios decommission).
=> #772 Removing kickstart launch

lib/units/ios-device/plugins/info/index.js, lib/units/ios-device/plugins/screen/stream.js, lib/units/ios-device/plugins/wda/WdaClient.js, lib/wire/wire.proto, res/app/components/stf/device/enhance-device/enhance-device-service.js
The following code creates the 'preparing' state in `wire.proto` , and uses this status code when WDA is starting.
=> #410 Change state to preparing on WDA startup

lib/units/ios-device/plugins/info/index.js, lib/units/ios-device/plugins/screen/stream.js, lib/units/ios-device/plugins/wda/WdaClient.js, lib/wire/wire.proto, res/app/components/stf/device/enhance-device/enhance-device-service.js
=> Revert "#410 Change state to preparing on WDA startup"

lib/units/ios-device/plugins/solo.js, lib/units/ios-device/plugins/wda/WdaClient.js
The following PR correctly sets the device status according to the device connection.
=> #410 Adjusting status values when stopping/starting devices

lib/units/ios-device/plugins/screen/stream.js
reverting as approach with filtering corrupt the stream
=> Revert "#274 Identifying same and different frames to optimize stream"

lib/units/ios-device/plugins/devicenotifier.js, res/app/components/stf/device/enhance-device/enhance-device-service.js, res/app/device-list/column/device-column-service.js, res/app/device-list/icons/device-list-icons-directive.js
The following PR implements the Offline state when WDA crashes
=> #775 Add Offline status when WDA crashes

res/app/layout/cursor.css
The following PR enables text selection from device columns.
=> #785 Enable selectable text from Device columns

lib/wire/wire.proto, res/app/components/stf/device/device-info-filter/index.js, res/app/components/stf/device/enhance-device/enhance-device-service.js, res/app/device-list/column/device-column-service.js, res/app/device-list/icons/device-list-icons-directive.js
The following PR adds the Unhealthy status to STF, reusing `Unauthorized` colors
=> #483 Adding new Unhealthy status to STF

lib/units/ios-device/plugins/wda.js
The following code resets the device to portrait mode before using the home button
=> #801 Reset to portrait mode before pressing home button in iOS

lib/units/ios-device/plugins/wda.js
enabling home button for all rotations
=> #801 Home button hotfix

lib/units/ios-device/plugins/wda/WdaClient.js, res/app/control-panes/dashboard/navigation/navigation.pug
The following PR enables navigation input for iOS 17.
=> #140 Enabling navigation input for iOS 17+ devices

res/app/control-panes/dashboard/navigation/navigation.pug
This PR implements `<` operator
=> #140 Adjusting operator

lib/units/provider/index.js
The following PR catches register promise errors and ends with exit code 1
=> #827 Catch register error and exit process

res/app/device-list/details/device-list-details-directive.js, res/app/device-list/device-list-controller.js, res/app/settings/groups/devices/devices.pug, res/app/settings/groups/groups-controller.js
The following PR contains all the required logic to implement the following features:
1. Sorting each column independently 
2. Make rows draggable 
3. Include the user's sorting in `localStorage `
With these changes, row sorting will depend on the user preferences.
=> #816 Making sorting user-friendly

res/app/device-list/details/device-list-details-directive.js, res/app/settings/groups/groups-controller.js
The following PR adjusts status column behavior to correctly save info. about devices state when reloading.
=> #816 Fix for status column when reloading

res/app/components/stf/column-choice/column-choice-directive.js, res/app/device-list/details/device-list-details-directive.js
The following PR will reset to default column changes on startup
=> #816 Reset columns in startup and fix for busy devices when reloading

res/app/device-list/details/device-list-details-directive.js, res/app/device-list/stats/device-list-stats-directive.js
The following PR fixes:
- Showing `Stop Using` when a device is being used
- Refreshing correct number of busy devices automatically
=> #816 Fix for busy state in device row

res/app/components/stf/screen/screen-directive.js
The following PR performs a fast reload to get a device size before any screen inputs.
=> #556 perform fast reload and get new size data

lib/units/provider/index.js
The following PR replaces exit code 0 to exit code 1 after Unhealthy status.
=> #873 Replace exit code 0 to exit code 1

lib/units/device/index.js
The following PR ends process on 'no service started' error with code 0.
=> #868 Exit code 0 for 'no service started'

lib/units/ios-device/plugins/wda/WdaClient.js
The following PR differentiates between DB values and WDA ones.
=> #877 Fix to control UI when reusing device size

res/app/device-list/details/device-list-details-directive.js
The following PR stores the user scrolling Y coordinates on the details tab.
=> #871 store user scrolling on details

res/app/device-list/details/device-list-details-directive.js, res/app/menu/menu-controller.js, res/app/menu/menu.pug
The following PR reuses previous scrolling state after using a device or reloading.
=> #871 Reuse scrolling status on reload and $location changes

res/app/device-list/details/device-list-details-directive.js
The following PR sets the correct attribute value to make table rows text selectable in every column.
=> #869 Correct attribute to make rows text selectable

res/app/device-list/details/device-list-details-directive.js
The following PR handles the contextmenu event to properly copy the text on right click.
=> #869 Handle contextmenu event

res/app/menu/menu-controller.js
The following PR implements the correct support email when clicking 'Contact Support'
=> #839 Use correct support email

lib/db/api.js
The following PR sets the method with default values
=> #915 fix for saveDeviceInitialState method

res/app/device-list/column/device-column-service.js
The following PR sets the same value for Product/Model columns with the following priority: `name -> model -> serial`
=> #918 Set the same values for product/model columns

lib/db/api.js, lib/units/ios-device/plugins/group.js, lib/units/ios-device/plugins/wda/WdaClient.js, lib/units/processor/index.js, res/app/components/stf/screen/screen-directive.js
The following PR implements fixes for #923 and #924, as well as storing size and type info. on first session through `group.js`
=> #923 and #924 fixes, storing info. on first session

res/app/components/stf/basic-mode/basic-mode-directive.js, res/app/menu/menu.css, res/app/menu/menu.pug, res/app/views/index.pug, res/web_modules/angular-borderlayout/style.css
The following PR allows using the navigation bar in Mobile STF
=> #943 Display Navigation bar correctly in Mobile

res/app/device-list/details/device-list-details-directive.js
The following PR fixes the empty filters error on first STF session.
=> #953 fix for device filters

res/app/control-panes/control-panes.pug
The following PR will display the STF screen correctly.
=> #956 Display STF screen correctly

res/app/control-panes/control-panes.pug
The following PR implements navigation tabs for Mobile without breaking the existing Standalone window feature.
=> #942 Display navigation tabs for Mobile

res/app/control-panes/control-panes.pug
The following PR allows to use the device control bottom panel.
=> #961 Display bottom panel correctly

res/auth/ldap/scripts/signin/signin.pug, res/auth/mock/scripts/signin/signin.pug, res/auth/zebrunner/scripts/signin/signin.pug
The following PR implements a better auth. error message in the login route.
=> #850 Improve login auth. error message

lib/units/ios-device/plugins/group.js
The following PR changes the condition for devices first session
=> #971 change condition on first session

res/app/device-list/column/device-column-service.js, res/app/device-list/details/device-list-details-directive.js
The following PR will display size in the devices list after first session.
=> #940 Update data from a new device in the list

res/app/device-list/details/device-list-details-directive.js
The following PR will check for any special characters inside the `tbody`
=> #978 Case for special characters

lib/units/ios-device/plugins/screen/stream.js, res/app/components/stf/screen/screen-directive.js, res/app/components/stf/screen/screen-loader/screen-loader.css
The following PR implements an adapted loading icon animation during swipes
=> #980 Implement loading icon during swipe

res/app/control-panes/device-control/device-control-controller.js
The following PR will add a 'blink' after the rotation was done.
=> #892 Change rotation icon smoothly

res/app/components/stf/tokens/generate-access-token/generate-access-token-directive.js
The following PR will prevent submitting data if no token title is provided.
=> #880 Prevent submit on blank space

lib/units/websocket/index.js, res/app/components/stf/tokens/access-token-service.js, res/app/components/stf/tokens/generate-access-token/generate-access-token-directive.js, res/app/settings/keys/access-tokens/access-tokens-controller.js, res/app/settings/keys/access-tokens/access-tokens.pug
The following PR will clear the token input form and delete selected tokens based on their id.
=> #880 Handle token data correctly

res/app/settings/general/date-format/date-format-controller.js, res/app/settings/general/date-format/date-format.pug
The following PR will check if the chars are valid for the date format.
=> #844 Improving date input

res/app/control-panes/device-control/device-control.pug
The following PR allows to use the device top bar in mobile
=> #833 Display device top bar correctly

res/app/settings/general/date-format/date-format-controller.js
=> #844 Add missing char. in validChars

lib/units/ios-device/plugins/wda.js
The following PR allows to use the home button in mobile.
=> #990 Mobile: home button fix

res/app/components/stf/screen/screen-directive.js
The following PR allows to tap in the correct positions in mobile.
=> #992 Mobile: tap fixes

res/app/components/stf/landscape/landscape-directive.js
The following PR should disable the device rotation when the screen position changes.
=> #996 Mobile: Fix moving screen behavior

res/app/device-list/details/device-list-details-directive.js
With this PR devices are positioned correctly.
=> #1002 Mobile: cancel auto scroll

res/web_modules/nine-bootstrap/nine-bootstrap.scss
The following PR will display the correct styles after pressing 'stop using' button
=> #995 Mobile: 'use' button correct styles

res/app/control-panes/advanced/advanced.pug, res/app/control-panes/control-panes.css, res/app/control-panes/control-panes.pug, res/app/control-panes/dashboard/dashboard.pug, res/app/control-panes/index.js, res/app/menu/menu.css, res/app/menu/menu.pug, res/app/views/index.pug
The following PR enables a caption for STF routes (4 buttons in the bottom)
=> #997 Mobile: Caption for Stf routes

res/app/control-panes/device-control/device-control-controller.js, res/app/device-list/details/device-list-details-directive.js, res/app/device-list/device-list.pug, res/app/group-list/group-list.css, res/app/menu/menu.pug, res/app/views/index.pug
The following PR fixes style and scroll-logic issues for mobile use.
=> Mobile: fixes for #997, #1002, #1007

res/app/device-list/stats/device-list-stats.css, res/app/layout/small.css, res/app/menu/menu.css, res/app/menu/menu.pug
The following PR contains compatible styles with android devices.
=> Mobile: fixes for Android (#997, #1002, #1007)

res/app/layout/small.css
The following will display the rotation buttons correctly in mobile
=> #1011 remove button changes

res/app/components/stf/screen/screen-directive.js
The following PR adjusts the canvas size when the first image is detected
=> #994 Testing: adjust canvas size on new Image detection

res/app/components/stf/screen/screen-directive.js
=> #994 Testing: reducing canvas size by 5%

res/app/components/stf/screen/screen-directive.js
The following PR will adjust the canvas size to a working value and try to adjust the image size inside the canvas.
=> #994 Testing: adjusting canvas image size

res/app/components/stf/screen/screen-directive.js
=> #994 Set image size to canvas size

res/app/components/stf/screen/screen-directive.js
=> #994 Redraw canvas image on exceeded canvas size

res/app/components/stf/screen/screen-directive.js
=> #994 Testing: condition fix and draw image revert

res/app/control-panes/device-control/device-control-controller.js
The following PR will switch rotation buttons without waiting on mobile
=> #996 timeout exception for basicmode

res/app/device-list/column/device-column-service.js
=> Revert "#918 using underscores for device name"

res/app/control-panes/info/info.pug, res/app/device-list/column/device-column-service.js
the variable should be loaded and use the correct `device.name` value in the app.
=> #918 using enhancedName var.

lib/util/datautil.js
The following PR will prevent using the matching device name from stf devices DB.
=> #918 handle case for matching device name

lib/units/api/controllers/devices.js
The following PR will allow to use the correct `device.name` value from stf API
=> #918 Return correct device name from API
