zebrunner/stf

Dockerfile
docker/armv7l/Dockerfile

`6.11.2` version doesn't available right now. Need to use latest version from v.6.x.

Bump node.js to v6.17.1

---

lib/units/ios-device/plugins/wda/WdaClient.js

Update wdaClient output logs due to client wishes 
```
My wishes:
a) print to log info about get/post request
b) show actual values in log instead of "${this.sessionId}"
c) show in log each implemented wda command
```

Has been updated wdaClient logs output.

---

lib/units/device/plugins/screen/stream.js

**Steps to repro bug**
1. Open any android device.
2. reload the page by clicking cmd/cntrl + R.
**Actual result:**
Error modal appears.
**Expected behavior:**
Page reloads without error message.
**The flow**
Websocket server doesn't have error handler.

Have been added error handler for WebSocker server connection

---

lib/units/ios-device/plugins/util/iosutil.js
lib/units/ios-device/plugins/wda/WdaClient.js

**have been fixed issue with home btn**
WDA's endpoint `${ip}/session/${session_id}/wda/keys` - with body `{value: ['home']}` works super slow at ios 13.1, so this endpoint for home button has replaced in preference -  `${ip}/wda/homescreen`

#81: have been fixed issue with home btn

---

lib/units/ios-device/plugins/devicenotifier.js
lib/units/ios-device/plugins/screen/stream.js
res/app/components/stf/common-ui/modals/temporarily-unavialable/temporarily-unavialable-service.js
res/app/components/stf/screen/screen-directive.js
res/app/components/stf/socket/socket-service.js

Have been updated ios-device service, these changes make service more independent of WDA and in the case of WDA's disconnection, the process will not stop(kill) itself.

Istf #108 make ios device completely independent of wda

---

lib/units/ios-device/plugins/wda/WdaClient.js

The following modifications prevent different crashes disabling specific requests, since not all the endpoints are available in Apple TV devices. Depending on what direction the user taps, the device will press a button towards the tap direction.

#688 Incorporate tap and keys with Apple TV buttons. Preventing Apple TV crashes.

---

lib/units/ios-device/plugins/util/iosutil.js

The following PR fixes typos inside `iosutil`, with this code Volume buttons and the Mute button will work. Since media buttons don't exist in WDA, the following code contains different `log.error()` to avoid crashes.

#465 Volume/Mute button fixes. Preventing media buttons crashes

---

lib/units/ios-device/plugins/wda/WdaClient.js

In order to choose any name for the devices, it's necessary to change the following `if` statements.

#688 Conditionals Fix

---

lib/units/ios-device/plugins/util/iosutil.js
lib/units/ios-device/plugins/wda/WdaClient.js

The following modifications allow dpad keys to work in Apple TV devices. Since dpad keys were not used, their `return` value will still be blank strings.

#688 Dpad keys fix.

---

res/app/control-panes/advanced/input/input.pug

The following code disables 'switch charset' button for iOS devices, preventing crashes.

#463 Disabling switch charset button for iOS devices

---

res/app/control-panes/dashboard/install/install.pug

The following modifications prevent the error message from being outside of its container.

#404 Adjusting error message styles

---

lib/units/ios-device/plugins/wda.js
res/app/components/stf/control/control-service.js
res/app/control-panes/dashboard/navigation/navigation.pug

The following code disables the reset browser button for iOS devices. It also prevents a console error when pressing the button with any iOS devices (inside `this.clearBrowser` ), which will be necessary if there's future implementation in WDA.
**Related thread:** https://github.com/facebookarchive/WebDriverAgent/issues/502

#464 Disabling Reset browser button for iOS devices

---

res/app/components/stf/device-context-menu/device-context-menu.pug

The following code disables back and recents buttons in iOS devices, since these are currently unavailable in wda.

#728 Disabling Back and Recents buttons in iOS devices

---

lib/units/ios-device/plugins/wda/WdaClient.js
res/app/control-panes/dashboard/navigation/navigation.pug

The following modifications disable the url navigation for iOS since it works incorrectly: https://github.com/appium/appium/issues/13975

#140 Disabling navigation for iOS. Related issue in comments

---

res/app/control-panes/dashboard/navigation/navigation.pug

The following code disables the url navigation `input` for iOS devices.

#140 Disabling navigation input

---

res/app/components/stf/device-context-menu/device-context-menu.pug

Since the tags are <a> or links, the `disabled` has no effect on it. The following modification adjusts this by hiding the element through the attribute `display`

#728 Hiding crashing links for iOS

---

lib/units/ios-device/plugins/wda/WdaClient.js
res/app/components/stf/screen/screen-directive.js
res/app/control-panes/device-control/device-control.css

The following commit fixes device styles in `landscape` mode, and adds an `orientation` property in WdaClient

#177 Testing fixes for device rotation styles, adding orientation property in WdaClient

---

lib/units/ios-device/plugins/wda/WdaClient.js

The following adjustment fixes the blue button for Apple TV devices.

#749 Fixing home button for Apple TV

---

res/app/control-panes/dashboard/clipboard/clipboard.pug
res/app/control-panes/device-control/device-control.pug

The following PR disables crashing buttons in Apple TV devices.

#754 Disabling crashing buttons (Apple TV)

---

lib/units/ios-device/plugins/wda.js
lib/units/ios-device/plugins/wda/WdaClient.js

The following code fixes an error in RotationIosEvent, now the device width/height are passed to the event when a rotation happens. The device coordinates still work incorrectly in Landscape mode

#177 Draft: Fixing error in RotationIosEvent

---

lib/units/ios-device/plugins/util/iosutil.js
lib/units/ios-device/plugins/wda/WdaClient.js
res/app/control-panes/advanced/input/input.pug

The following code implements a `switchCharset()` method in WdaClient.js, which is triggered whenever the switch charset button is clicked. The method changes `this.upperCase` variable as false/true, depending on its value `typeKey()` method will send uppercased keys.
It also disables the button for AppleTV devices.

#463 Adding Switch Charset function for WDA client

---

lib/units/ios-device/plugins/wda/WdaClient.js

The following code skips the error lock crash, so the device keeps working correctly

#762 16.1 devices locking fix

---

lib/units/ios-device/plugins/wda/WdaClient.js

The following code prevents a crash when trying to rotate the device in an App. where rotation is not enabled, preventing the following error: `Unable To Rotate Device`

#765 Skip iOS rotation crash

---

lib/units/ios-device/plugins/screen/stream.js
lib/units/ios-device/plugins/util/iosutil.js
lib/units/ios-device/plugins/wda/WdaClient.js

The following PR includes:
- A new request to `/rotation` endpoint before closing session (reset to Portrait)
- A new `orientationToDegrees` method in iosutil
- A `return` statement to `stopSession` method
- Using `RotationEvent` to correctly update the new rotation values 
- Improving error message handling

#770 Fixing Landscape when closing device (reset to Portrait mode)

---

lib/units/ios-device/plugins/screen/stream.js

When starting WDA, rotation will be skipped for AppleTV devices.

#770 Adding exception for tvOS

---

lib/units/ios-device/plugins/solo.js
lib/units/ios-device/plugins/wda/WdaClient.js
lib/wire/wire.proto
res/app/components/stf/device/enhance-device/enhance-device-service.js
res/app/device-list/column/device-column-service.js
res/app/device-list/icons/device-list-icons-directive.js

The following PR includes:
- A new device status code (6), used when starting WDA.
- A `setStatus` method in WdaClient to change the device status dynamically.
- When the session starts, the status is set to 3.
- In the `enhanceDevice` function, the UI will be change to 'Preparing' state to 'Available' state dynamically.
- 'Preparing' state reuses green font for the text (same as Android)

#410 Adding 'Preparing' state to iOS devices on WDA startup

---

lib/units/ios-device/plugins/screen/stream.js

The following code identifies old and new frames, if the frame is a new one, the frame is pushed to the pipeline and then processed in the stream.

#274 Identifying same and different frames to optimize stream

---

lib/units/ios-device/plugins/wda.js
lib/units/ios-device/plugins/wda/WdaClient.js

The following PR resets the device to Portrait mode before sending the Home button request, as well as setting the device coordinates to Portrait mode

#801 Reset device to Portrait mode coordinates when pressing home button

---

lib/units/ios-device/plugins/util/iosutil.js
res/app/control-panes/info/info-controller.js
res/app/control-panes/info/info.pug

The following PR enables Find device button for ios and uses the Finder app. bundleId correctly

#469 Enabling 'Find' button for iOS

---

lib/units/api/index.js

The following PR adjusts the amount of listeners in `channelRouter`

[Draft] #818 Set api maxlisteners to 100

---

lib/units/ios-device/plugins/wda/WdaClient.js

The following PR checks if swipe operation is finished and if `deviceSize` values are set before sending other screen requests

#817 Lock screen until swipe is finished

---

lib/units/provider/index.js

The following PR adds a `catch` to the adb client `trackDevices` promise.

#827 Catching adb client

---

res/app/components/stf/device/enhance-device/enhance-device-service.js
res/app/device-list/column/device-column-service.js
res/app/device-list/details/device-list-details-directive.js
res/app/device-list/icons/device-list-icons-directive.js

The following PR does the following:
- Sorts all devices in `Devices` page correctly
- Replaces `enhancedName` with `device.name | device.product`
- Compares model names with `localCompare`
- Instantly assigns device as busy on click

#816 fixes for four issues

---

lib/units/provider/index.js

The following code implements other `lifecycle` method and adds a small delay to exit after `Unhealthy` status req.

#847 exit 0 code and small delay to change status

---

lib/db/api.js
lib/units/api/controllers/devices.js
lib/units/api/swagger/api_v1.yaml
lib/units/api/swagger/api_v1_generated.json
lib/units/ios-device/plugins/wda/WdaClient.js
lib/wire/wire.proto

The following PR implements: 
- A new `scale` property in the device `display` object.
- A new endpoint in `/api/v1` to get the device's size/scale values.
- Reusing RethinkDB data to skip WDA calls.

#556 Reusing existing size values from RethinkDB

---

res/app/components/stf/device/enhance-device/enhance-device-service.js

The following PR allows to set `Unhealthy` and `Offline` status correctly if needed in Android devices.

#847 Fix for displaying Unhealthy status correctly in Android

---

lib/units/ios-device/plugins/wda/WdaClient.js

The following PR skips an error message when unlocking iOS 17+ devices, preventing crash.

#864 Skip error message when unlocking device

---

lib/units/ios-device/plugins/wda.js
lib/units/ios-device/plugins/wda/WdaClient.js

In this PR I added an error catch for `home` button when rotating and a `wdaClient` property to detect when the device is already rotating.

#875 Wait for rotation event to finish

---

res/app/device-list/device-list-controller.js

The following PR hides the model name column by default.

#451 Hide model column by default

---

lib/units/api/controllers/devices.js
lib/units/ios-device/plugins/wda/WdaClient.js

The following code returns `0` values for `width, height, scale` in API call if there are no values stored yet. 
It also improves the `size` method error handling to catch STF API errors (if any)

#883 Return '0' values when empty DB size, improve size method

---

res/app/components/stf/screen/screen-directive.js
res/app/device-list/details/device-list-details-directive.js
res/app/device-list/device-list-controller.js
res/app/device-list/icons/device-list-icons-directive.js

The following PR uses `localStorage` to set user's filtering data. It also implements a better approach to reload with `route`.

#846 save filtering on refresh

---

lib/db/api.js
lib/units/api/controllers/devices.js
lib/units/api/swagger/api_v1.yaml

The following PR allows to: 
1. Show correct group owner values in STF
2. Get group owner values from STF API in: `{baseUrl}/api/v1/devices/{serial}/owner`
This endpoint is necessary to get those values in agent servers.

#554 Set correct owner .env values, new STF API owner endpoint

---

lib/units/ios-device/plugins/wda/WdaClient.js
res/app/components/stf/screen/screen-directive.js

The following PR implements a valid `window` method to use with mcloud-device containers and properly set DB size/scale values.

#556 Using webapi method and detecting null orientation

---

lib/cli/ios-device/index.js
lib/db/api.js
lib/units/api/controllers/devices.js
lib/units/api/swagger/api_v1.yaml
lib/units/ios-device/plugins/info/index.js
lib/units/ios-device/plugins/screen/stream.js
lib/units/ios-device/plugins/wda/WdaClient.js
lib/units/processor/index.js
lib/wire/wire.proto

The following PR includes:
1. Removing `device-type` detection from `ios-device` cli args. Instead, using `wdaClient.deviceType`.
2. Using `deviceType` property from DB and use it in WdaClient (`wdaClient.deviceType = response.deviceType`)
3. Setting `deviceType` property in RethinkDB if it doesn't exist.
4. Review all exceptional cases for AppleTV to use `wdaClient.deviceType`  
5. A new endpoint for STF API: `<baseUrl>/api/v1/devices/<udid>/type`. Which returns: `{"deviceType": "iPhone"}` or `{"deviceType": "Apple TV"}` on success.
6. A new `dbapi.getDeviceType(serial)` method which returns the device type.

#897 Detecting device type from DB without breaking functionalities

---

lib/units/ios-device/plugins/info/index.js

The following PR excludes `reject` from the catch method. Since the first must be inside the promise context.

#911 catch error correctly in device info.

---

lib/units/api/controllers/devices.js
lib/units/ios-device/plugins/wda/WdaClient.js

The following PR handles the first device session and awaits for the values to be set, and handles the case where `deviceType` does not exist in DB yet. It also improves WdaClient socket connection code and prevents crashes when `err.error.value.message` does not exist

#556 and #897 fixes on first session, defining error messages correctly

---

res/app/control-panes/screenshots/screenshots-controller.js

The following PR disables Screenshot button when clicked. After 3 seconds, it is enabled for use again.
This prevents overloading appium with screenshot requests and causing the `'Failed to grow buffer'` error

#934 Disable screenshot button for 3s

---

res/app/control-panes/device-control/device-control-controller.js
res/app/menu/menu-controller.js

The following PR allows to reload the device data state, in order to handle the `device.using` property as false. 
It also fixes a console error for the contact email variable.

#930 Stop using and show 'Use' button correctly

---

lib/units/ios-device/plugins/util/iosutil.js
res/app/control-panes/advanced/input/input-controller.js
res/app/control-panes/advanced/input/input.pug

The following PR disables mute button for 16s after use, and a small delay between every `pressButton` request.
This prevents overloading appium with `pressButton` requests and causing the 'Failed to grow buffer' error

#938 Temporary disabling mute button after use

---

res/app/components/stf/basic-mode/basic-mode.css
res/app/control-panes/control-panes.pug
res/app/device-list/device-list.pug

The following PR allows to see/use the `Details` and `Customize` buttons with adapted styles for mobile

#944 Make 'Details' and 'Customize' visible in Mobile

---

lib/units/ios-device/plugins/group.js

The following PR detects the device type based on its model or its name (in case the first isn't valid), and then setting `deviceType` to `Apple TV` or `iPhone` in the DB.

#967 Set device type based on model or name

---

lib/cli/ios-device/index.js
lib/units/ios-device/plugins/group.js
lib/units/ios-device/plugins/util/iosutil.js
lib/units/ios-device/plugins/wda/WdaClient.js

The following PR allows to display battery and version info. after the first device setup. It also improves the `iosutil` with new methods.

#849 Display battery and version info. properly

---

res/app/device-list/column/device-column-service.js
res/app/device-list/details/device-list-details-directive.js
res/app/device-list/device-list.css

The following PR moves the edit icon to the left side in each note cell.

#973 Move edit icon to left 

---

res/app/components/stf/screen/screen-directive.js

The following PR could avoid the grey canvas error in some iOS devices, preventing this error:
`Canvas area exceeds the maximum limit (width * height > 16777216).`

#994 Testing: reduce canvas size if exceeded

---

res/app/components/stf/screen/screen-directive.js
res/app/control-panes/device-control/device-control.pug
res/web_modules/nine-bootstrap/nine-bootstrap.scss

The following PR displays the rotation buttons as active in mobile and switches canvas (if exceeded) size on landscape

#996 Fix for rotation icons styles and exceeded canvas on landscape

---

res/app/device-list/column/device-column-service.js

The following PR will detect blank spaces and use `_` for product / model columns

#918 using underscores for device name

---

res/app/components/stf/screen/screen-directive.js

The following PR should prevent using a reduced canvas size when using iOS 18 devices

#1023 possible workaround to use ios18 in mobile

---

lib/units/ios-device/plugins/util/iosutil.js
res/app/components/stf/screen/screen-directive.js

The following PR will handle cases where `params.toX` and `params.toY` have big values (swipe made from Mobile), and will adjust their values.

#991: Workaround for mobile swipe in iOS

---

res/app/components/stf/device/enhance-device/enhance-device-service.js
res/app/control-panes/info/info.pug

The following PR will display the `device.model` value in Product. If there's no value, it will use `device.name`.

#918 Display correct device info. in manufacturer
